version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
  build:
    container_name: build
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"